
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"

  build:
    commands:
      - echo "Running Python Program..."
      - python main.py

post_build:
  commands:
    - echo "Build Completed Successfully"
